// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: experiment/experimentExecutor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteExperimentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Experiment *Experiment `protobuf:"bytes,1,opt,name=experiment,proto3" json:"experiment,omitempty"`
}

func (x *ExecuteExperimentRequest) Reset() {
	*x = ExecuteExperimentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_experiment_experimentExecutor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteExperimentRequest) ProtoMessage() {}

func (x *ExecuteExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_experiment_experimentExecutor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteExperimentRequest.ProtoReflect.Descriptor instead.
func (*ExecuteExperimentRequest) Descriptor() ([]byte, []int) {
	return file_experiment_experimentExecutor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteExperimentRequest) GetExperiment() *Experiment {
	if x != nil {
		return x.Experiment
	}
	return nil
}

type ExecuteExperimentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
}

func (x *ExecuteExperimentResponse) Reset() {
	*x = ExecuteExperimentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_experiment_experimentExecutor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteExperimentResponse) ProtoMessage() {}

func (x *ExecuteExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_experiment_experimentExecutor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteExperimentResponse.ProtoReflect.Descriptor instead.
func (*ExecuteExperimentResponse) Descriptor() ([]byte, []int) {
	return file_experiment_experimentExecutor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteExperimentResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

var File_experiment_experimentExecutor_proto protoreflect.FileDescriptor

var file_experiment_experimentExecutor_proto_rawDesc = []byte{
	0x0a, 0x23, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x1a, 0x1b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52,
	0x0a, 0x18, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x35, 0x0a, 0x19, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x32, 0x78, 0x0a, 0x12, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12,
	0x62, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x75, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_experiment_experimentExecutor_proto_rawDescOnce sync.Once
	file_experiment_experimentExecutor_proto_rawDescData = file_experiment_experimentExecutor_proto_rawDesc
)

func file_experiment_experimentExecutor_proto_rawDescGZIP() []byte {
	file_experiment_experimentExecutor_proto_rawDescOnce.Do(func() {
		file_experiment_experimentExecutor_proto_rawDescData = protoimpl.X.CompressGZIP(file_experiment_experimentExecutor_proto_rawDescData)
	})
	return file_experiment_experimentExecutor_proto_rawDescData
}

var file_experiment_experimentExecutor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_experiment_experimentExecutor_proto_goTypes = []any{
	(*ExecuteExperimentRequest)(nil),  // 0: experiment.ExecuteExperimentRequest
	(*ExecuteExperimentResponse)(nil), // 1: experiment.ExecuteExperimentResponse
	(*Experiment)(nil),                // 2: experiment.Experiment
}
var file_experiment_experimentExecutor_proto_depIdxs = []int32{
	2, // 0: experiment.ExecuteExperimentRequest.experiment:type_name -> experiment.Experiment
	0, // 1: experiment.ExperimentExecutor.ExecuteExperiment:input_type -> experiment.ExecuteExperimentRequest
	1, // 2: experiment.ExperimentExecutor.ExecuteExperiment:output_type -> experiment.ExecuteExperimentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_experiment_experimentExecutor_proto_init() }
func file_experiment_experimentExecutor_proto_init() {
	if File_experiment_experimentExecutor_proto != nil {
		return
	}
	file_experiment_experiment_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_experiment_experimentExecutor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ExecuteExperimentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_experiment_experimentExecutor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ExecuteExperimentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_experiment_experimentExecutor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_experiment_experimentExecutor_proto_goTypes,
		DependencyIndexes: file_experiment_experimentExecutor_proto_depIdxs,
		MessageInfos:      file_experiment_experimentExecutor_proto_msgTypes,
	}.Build()
	File_experiment_experimentExecutor_proto = out.File
	file_experiment_experimentExecutor_proto_rawDesc = nil
	file_experiment_experimentExecutor_proto_goTypes = nil
	file_experiment_experimentExecutor_proto_depIdxs = nil
}
