// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: experiment/experimentStateController.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveExperimentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Experiment *Experiment `protobuf:"bytes,1,opt,name=experiment,proto3" json:"experiment,omitempty"`
}

func (x *SaveExperimentRequest) Reset() {
	*x = SaveExperimentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_experiment_experimentStateController_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveExperimentRequest) ProtoMessage() {}

func (x *SaveExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_experiment_experimentStateController_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveExperimentRequest.ProtoReflect.Descriptor instead.
func (*SaveExperimentRequest) Descriptor() ([]byte, []int) {
	return file_experiment_experimentStateController_proto_rawDescGZIP(), []int{0}
}

func (x *SaveExperimentRequest) GetExperiment() *Experiment {
	if x != nil {
		return x.Experiment
	}
	return nil
}

type SaveExperimentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveExperimentResponse) Reset() {
	*x = SaveExperimentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_experiment_experimentStateController_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveExperimentResponse) ProtoMessage() {}

func (x *SaveExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_experiment_experimentStateController_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveExperimentResponse.ProtoReflect.Descriptor instead.
func (*SaveExperimentResponse) Descriptor() ([]byte, []int) {
	return file_experiment_experimentStateController_proto_rawDescGZIP(), []int{1}
}

var File_experiment_experimentStateController_proto protoreflect.FileDescriptor

var file_experiment_experimentStateController_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x45, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x76, 0x0a, 0x19, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x59, 0x0a,
	0x0e, 0x53, 0x61, 0x76, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x21, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x75, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_experiment_experimentStateController_proto_rawDescOnce sync.Once
	file_experiment_experimentStateController_proto_rawDescData = file_experiment_experimentStateController_proto_rawDesc
)

func file_experiment_experimentStateController_proto_rawDescGZIP() []byte {
	file_experiment_experimentStateController_proto_rawDescOnce.Do(func() {
		file_experiment_experimentStateController_proto_rawDescData = protoimpl.X.CompressGZIP(file_experiment_experimentStateController_proto_rawDescData)
	})
	return file_experiment_experimentStateController_proto_rawDescData
}

var file_experiment_experimentStateController_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_experiment_experimentStateController_proto_goTypes = []any{
	(*SaveExperimentRequest)(nil),  // 0: experiment.SaveExperimentRequest
	(*SaveExperimentResponse)(nil), // 1: experiment.SaveExperimentResponse
	(*Experiment)(nil),             // 2: experiment.Experiment
}
var file_experiment_experimentStateController_proto_depIdxs = []int32{
	2, // 0: experiment.SaveExperimentRequest.experiment:type_name -> experiment.Experiment
	0, // 1: experiment.ExperimentStateController.SaveExperiment:input_type -> experiment.SaveExperimentRequest
	1, // 2: experiment.ExperimentStateController.SaveExperiment:output_type -> experiment.SaveExperimentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_experiment_experimentStateController_proto_init() }
func file_experiment_experimentStateController_proto_init() {
	if File_experiment_experimentStateController_proto != nil {
		return
	}
	file_experiment_experiment_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_experiment_experimentStateController_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SaveExperimentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_experiment_experimentStateController_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SaveExperimentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_experiment_experimentStateController_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_experiment_experimentStateController_proto_goTypes,
		DependencyIndexes: file_experiment_experimentStateController_proto_depIdxs,
		MessageInfos:      file_experiment_experimentStateController_proto_msgTypes,
	}.Build()
	File_experiment_experimentStateController_proto = out.File
	file_experiment_experimentStateController_proto_rawDesc = nil
	file_experiment_experimentStateController_proto_goTypes = nil
	file_experiment_experimentStateController_proto_depIdxs = nil
}
