// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: mra/mra.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent is an MRA agent
type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Demand int32    `protobuf:"varint,2,opt,name=demand,proto3" json:"demand,omitempty"`
	Acc    []string `protobuf:"bytes,3,rep,name=acc,proto3" json:"acc,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mra_mra_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_mra_mra_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_mra_mra_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetDemand() int32 {
	if x != nil {
		return x.Demand
	}
	return 0
}

func (x *Agent) GetAcc() []string {
	if x != nil {
		return x.Acc
	}
	return nil
}

// MRA is an MRA scenario
type MRA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Agents    []*Agent `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	Resources []string `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *MRA) Reset() {
	*x = MRA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mra_mra_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MRA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRA) ProtoMessage() {}

func (x *MRA) ProtoReflect() protoreflect.Message {
	mi := &file_mra_mra_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRA.ProtoReflect.Descriptor instead.
func (*MRA) Descriptor() ([]byte, []int) {
	return file_mra_mra_proto_rawDescGZIP(), []int{1}
}

func (x *MRA) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MRA) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *MRA) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_mra_mra_proto protoreflect.FileDescriptor

var file_mra_mra_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x72, 0x61, 0x2f, 0x6d, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6d, 0x72, 0x61, 0x22, 0x41, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64,
	0x65, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x63, 0x63, 0x22, 0x57, 0x0a, 0x03, 0x4d, 0x52, 0x41, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x6d, 0x72, 0x61, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x42, 0x0a, 0x5a, 0x08, 0x75, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mra_mra_proto_rawDescOnce sync.Once
	file_mra_mra_proto_rawDescData = file_mra_mra_proto_rawDesc
)

func file_mra_mra_proto_rawDescGZIP() []byte {
	file_mra_mra_proto_rawDescOnce.Do(func() {
		file_mra_mra_proto_rawDescData = protoimpl.X.CompressGZIP(file_mra_mra_proto_rawDescData)
	})
	return file_mra_mra_proto_rawDescData
}

var file_mra_mra_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mra_mra_proto_goTypes = []any{
	(*Agent)(nil), // 0: mra.Agent
	(*MRA)(nil),   // 1: mra.MRA
}
var file_mra_mra_proto_depIdxs = []int32{
	0, // 0: mra.MRA.agents:type_name -> mra.Agent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mra_mra_proto_init() }
func file_mra_mra_proto_init() {
	if File_mra_mra_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mra_mra_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mra_mra_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MRA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mra_mra_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mra_mra_proto_goTypes,
		DependencyIndexes: file_mra_mra_proto_depIdxs,
		MessageInfos:      file_mra_mra_proto_msgTypes,
	}.Build()
	File_mra_mra_proto = out.File
	file_mra_mra_proto_rawDesc = nil
	file_mra_mra_proto_goTypes = nil
	file_mra_mra_proto_depIdxs = nil
}
