// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseReader() {
  return window['go']['main']['App']['CloseReader']();
}

export function GenerateMRA(arg1, arg2) {
  return window['go']['main']['App']['GenerateMRA'](arg1, arg2);
}

export function InitialiseReader() {
  return window['go']['main']['App']['InitialiseReader']();
}

export function ReadAllExperimentMetadata() {
  return window['go']['main']['App']['ReadAllExperimentMetadata']();
}

export function ReadExperimentResult(arg1) {
  return window['go']['main']['App']['ReadExperimentResult'](arg1);
}

export function RunExperiment(arg1) {
  return window['go']['main']['App']['RunExperiment'](arg1);
}

export function SaveExperiment(arg1) {
  return window['go']['main']['App']['SaveExperiment'](arg1);
}

export function SetAppContext(arg1) {
  return window['go']['main']['App']['SetAppContext'](arg1);
}
