// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExperiment(arg1) {
  return window['go']['main']['App']['AddExperiment'](arg1);
}

export function GenerateMRA(arg1, arg2) {
  return window['go']['main']['App']['GenerateMRA'](arg1, arg2);
}

export function GetAlgorithm() {
  return window['go']['main']['App']['GetAlgorithm']();
}

export function GetExperiments() {
  return window['go']['main']['App']['GetExperiments']();
}

export function RetrieveMetadata() {
  return window['go']['main']['App']['RetrieveMetadata']();
}

export function StoreExperiment(arg1) {
  return window['go']['main']['App']['StoreExperiment'](arg1);
}
