// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {experiment} from '../models';
import {proto} from '../models';
import {mra} from '../models';

export function AddExperiment(arg1:experiment.TSExperiment):Promise<void>;

export function GenerateMRA(arg1:Array<proto.Agent>,arg2:Array<string>):Promise<mra.MRA>;

export function GetAlgorithm():Promise<proto.SynthesisAlgorithm>;

export function GetExperiments():Promise<Array<proto.Experiment>>;

export function RetrieveMetadata():Promise<Array<experiment.Metadata>>;

export function StoreExperiment(arg1:proto.Experiment):Promise<void>;
